### ISSUE TITLE
Upload-Prozess

### ISSUE THREAD

**Issue by Alexsogge** [Alexsogge/MasterProject#10]
Soll der automatisiert oder manuell ablaufen? Ich hatte bisher nur Uploads erzeugen können, wenn ich die manuell gestartet hatte.

**Comment by Alexsogge** [comment]
Wird automatisch gestartet. War wahrswcheinlich ein Fehler der pre v0.9

**Comment by pscholl** [comment]
wenn automatisch funktioniert kann auch der knopf entfernt werden, und auch das conf fenster deaktiviert werden
