### ISSUE TITLE
For example, your notification does not provide enhanced functions to Wear OS users

### ISSUE THREAD

**Issue by pscholl** [Alexsogge/MasterProject#55]
Your app does not meet the minimum functionality requirements.
                        Please refer to Creating Wearable Apps, Creating Watch Faces
                        and / or Exposing Data to Complications documentation for more
                        information.
                          * For example, your notification does not provide enhanced
                            functions to Wear OS users

**Comment by Alexsogge** [comment]
probably refers to upload notification
