### ISSUE TITLE
«Save ZIP» und «Save MKV»

### ISSUE THREAD

**Issue by Alexsogge** [Alexsogge/MasterProject#6]
Wird MKV ausgewählt, dann stürzt die App ab

**Comment by Alexsogge** [comment]
MKV ist deprecated -> ungetested. Wenn erwünscht kann ich mich auf Fehlersuche machen

**Comment by pscholl** [comment]
da es soviel mehr Strom zieht, kanns deaktiviert werden...

**Comment by Alexsogge** [comment]
Reminder: Vermutlich ist das Problem, die gradle version, wodurch die .so nicht mehr in die apk gepackt wird
