### ISSUE TITLE
New authentication after update

### ISSUE THREAD

**Issue by swirth** [Alexsogge/MasterProject#61]
Ein Update der Software führt dazu, dass die Authentifizierung serverseitig erneut erteilt werden muss. Wenn das ein Proband/User durchführt, dann kann es lange dauern, bis die Authentifizierung erteilt wird.

Vorschlag: Authentifizierung/Token bliebt auf der Uhr gespeichert, wenn diese bereits einmal authentifiziert wurde (allenfalls im Filesystem ablegen, da App-Cache evtl. bei Neuinstallation mit gelöscht wird). Falls das nicht geht, dann muss eine Pushmeldung an Server-Admin erfolgen, damit dieser zeitnahe die Authentifizierung durchführt.

**Comment by Alexsogge** [comment]
Der ServerToken wird in den SharedPreferences gespeichert. Diese sollten bei einem Update eigentlich erhalten bleiben. Sicher, dass deine vorherige Version aus dem Playstore installiert war und nicht über ADB?
